language: go

go:
  - "1.14.1"

install:
  - curl -s -L https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz | tar zxv -C $GOPATH/bin --strip-components=1
  - glide install

script:
  - make test

cache:
  directories:
    - $HOME/gopath/src/github.com/syzspectroom/manta/replays
